In [204]:
import numpy as np

In [205]:
print(np.__version__)
np.show_config()


In [206]:
Z = np.zeros((10,10))
print(Z)
print(Z.nbytes)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
800


In [207]:
help(np.add)
np.info(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

In [208]:
Z[4]=1
Z[0,4]=1
print(Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [209]:
Z=np.arange(10,50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [210]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [211]:
Z=np.array([1,2,0,0,0,4,0])
print(np.nonzero(Z))

(array([0, 1, 5]),)


In [212]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [213]:
Z=np.random.random((3,3,3,3))

print(Z)

[[[[0.43147873 0.01613899 0.87340758]
   [0.70431424 0.8363845  0.16232601]
   [0.29231903 0.91977817 0.63329588]]

  [[0.55250573 0.76470989 0.55171635]
   [0.13838367 0.48683733 0.71422439]
   [0.745422   0.72499364 0.95920151]]

  [[0.41832213 0.47272226 0.9204247 ]
   [0.09031957 0.38025207 0.71335441]
   [0.71783424 0.96698273 0.82857448]]]


 [[[0.69608628 0.06373526 0.5882454 ]
   [0.69021628 0.49877772 0.35768142]
   [0.86077892 0.44864791 0.57829514]]

  [[0.01771328 0.70245108 0.42046597]
   [0.89394876 0.57307579 0.28426949]
   [0.09261492 0.37791648 0.04073065]]

  [[0.23589604 0.53431626 0.46767681]
   [0.63527977 0.14835319 0.59309776]
   [0.60878148 0.56461352 0.88199816]]]


 [[[0.78980869 0.66417789 0.68864471]
   [0.42967536 0.41685223 0.57251333]
   [0.08502275 0.80543908 0.71824766]]

  [[0.8416876  0.98347449 0.36625581]
   [0.73471558 0.37085653 0.28576306]
   [0.46365296 0.17047697 0.61025814]]

  [[0.24544489 0.47504425 0.29649741]
   [0.77796914 0.8850271  0.23

In [214]:
print("Minimum =",Z.min())
print("Maximum =",Z.max())
print(Z.mean())

Minimum = 0.016138986806610744
Maximum = 0.9834744886084104
0.5333000758908528


In [215]:
Z=np.ones((5,5))
Z[1:-1,1:-2]=0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [216]:
Z=np.ones((5,5))
Z=np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [217]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan - np.nan)
print(np.nan in set ([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [218]:
Z= np.diag([1,2,3,4])
print(Z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [219]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [220]:


print(np.unravel_index(99, (6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


Part 2

In [221]:
Z = np.tile([[0,1],[1,0]], (4,4))
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [222]:
Z = np.random.random((5,5))
Z = (Z - Z.min()) / (Z.max() - Z.min())
print(Z)

[[0.77837275 0.06676518 0.93421735 0.08743764 0.86487376]
 [0.32864444 0.44810923 0.53032287 0.58128723 0.62236254]
 [0.62056753 0.69956337 1.         0.10643332 0.13954873]
 [0.45370563 0.39477707 0.08497994 0.68381431 0.06105443]
 [0.05655813 0.72493786 0.         0.22197222 0.59506984]]


In [223]:

color = np.dtype([
    ("R", np.ubyte),
    ("G", np.ubyte),
    ("B", np.ubyte),
    ("A", np.ubyte)
])

print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


In [224]:

A = np.random.random((5,3))
B = np.random.random((3,2))

C = np.dot(A, B)
print(C)

# or
C = A @ B

[[1.70418931 0.61043672]
 [1.19163187 0.55002605]
 [1.12165448 0.39991123]
 [1.41232493 0.34325141]
 [1.60153227 0.49595338]]


In [225]:
Z = np.arange(11)
Z[(Z >= 3) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [226]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


In [227]:
Z=np.array([1,2,3,4])
print(np.sum(Z))
Z**Z          # legal
2 << Z >> 2   # legal
Z <- Z        # legal (parses as Z < (-Z))
1j * Z        # legal
Z/1/1         # legal


10


array([1., 2., 3., 4.])

In [228]:

print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_1277/1466865332.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
/tmp/ipykernel_1277/1466865332.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
/tmp/ipykernel_1277/1466865332.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [229]:

Z = np.array([-1.2, -3.7, 2.4, 5.9])
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-2. -4.  3.  6.]


In [230]:

A = np.array([1,2,3,4,5])
B = np.array([3,4,5,6,7])

print(np.intersect1d(A,B))

[3 4 5]


In [231]:

np.seterr(all='ignore')

# restore
np.seterr(all='warn')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [232]:

print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/tmp/ipykernel_1277/686884209.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


In [233]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')

print(yesterday)
print(today)
print(tomorrow)

2026-07-07
2026-07-08
2026-07-09


In [234]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [235]:
A = np.ones(3)
B = np.ones(3)*2

np.add(A, B, out=B)
np.divide(A, -2, out=A)
np.multiply(A, B, out=A)

print(A)

[-1.5 -1.5 -1.5]


In [236]:

Z = np.random.uniform(0,10,10)

print(Z.astype(int))
print(np.floor(Z))
print(np.trunc(Z))
print(Z//1)

[1 6 5 6 9 8 9 5 5 5]
[1. 6. 5. 6. 9. 8. 9. 5. 5. 5.]
[1. 6. 5. 6. 9. 8. 9. 5. 5. 5.]
[1. 6. 5. 6. 9. 8. 9. 5. 5. 5.]


In [237]:

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [238]:
def generate():
    for i in range(10):
        yield i

Z = np.fromiter(generate(), dtype=int)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [239]:
Z = np.linspace(0,1,12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [240]:

Z = np.random.random(10)
Z.sort()
print(Z)

# or
print(np.sort(Z))


[0.00685717 0.29958367 0.37614039 0.53480264 0.54144147 0.60753041
 0.7400799  0.93201979 0.9383659  0.94853872]
[0.00685717 0.29958367 0.37614039 0.53480264 0.54144147 0.60753041
 0.7400799  0.93201979 0.9383659  0.94853872]


In [241]:

Z = np.arange(10)
print(np.add.reduce(Z))


45


In [242]:

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

print(np.array_equal(A, B))

# or
print(np.all(A == B))


False
False


In [243]:
Z = np.zeros(10)
Z.flags.writeable = False

# Z[0] = 1   # Raises ValueError


In [244]:

Z = np.random.random((10,2))

X = Z[:,0]
Y = Z[:,1]

R = np.sqrt(X**2 + Y**2)
Theta = np.arctan2(Y, X)

print(R)
print(Theta)

[0.86354054 0.72666226 0.99407959 0.56714808 0.9376867  1.17473544
 0.89397499 0.89120015 0.26035216 0.99824399]
[0.89089435 0.68163997 0.50983182 0.28907683 1.26120201 0.6093238
 0.43028564 0.81181746 0.92293985 0.35481991]


In [245]:
Z = np.random.random(10)
Z[Z.argmax()] = 0

print(Z)

[0.89977349 0.1391118  0.08240043 0.67154457 0.79032148 0.85386145
 0.19794708 0.50541514 0.76986423 0.        ]


In [246]:
Z = np.zeros((10,10), dtype=[
    ('x', float),
    ('y', float)
])

Z['x'], Z['y'] = np.meshgrid(
    np.linspace(0,1,10),
    np.linspace(0,1,10)
)

print(Z)


[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [247]:
X = np.arange(8)
Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)

print(C)


[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


In [248]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(dtype)
    print(np.iinfo(dtype))
for dtype in [np.float16, np.float32, np.float64]:
    print(dtype)
    print(np.finfo(dtype))

<class 'numpy.int8'>
Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

<class 'numpy.int16'>
Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

<class 'numpy.int32'>
Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

<class 'numpy.int64'>
Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

<class 'numpy.float16'>
Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution 

In [249]:

np.set_printoptions(threshold=np.inf)
Z = np.arange(100)

print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [250]:
Z = np.random.uniform(0,100,10)
value = 37.5

index = (np.abs(Z-value)).argmin()

print(Z[index])


45.25542754202473


In [251]:
dtype = np.dtype([
    ('position', [('x', float), ('y', float)]),
    ('color', [('r', int), ('g', int), ('b', int)])
])

Z = np.zeros(5, dtype=dtype)

print(Z)


[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]


In [252]:
Z = np.random.random((100,2))

X = Z[:,0]
Y = Z[:,1]

dist = np.sqrt((X[:,None]-X)**2 + (Y[:,None]-Y)**2)

print(dist)


[[0.         0.67935534 0.70349992 0.54938595 0.10221476 0.4407691
  0.93467491 0.491213   0.71369021 0.74145141 0.7076961  0.56256216
  0.40564871 0.14611964 0.46447498 0.68218795 0.22462634 0.26257835
  0.54856377 0.34752529 0.26663878 0.28433253 0.90690409 0.69734682
  0.22590129 0.62491321 0.52555239 0.48885997 0.5230828  0.59633436
  0.28700639 0.27020506 0.68027836 0.17710291 0.64711477 0.34564747
  0.5666809  0.44084237 0.65019477 0.11497512 0.22576983 0.61818431
  0.61814864 0.45820549 0.08504667 0.53010897 0.26359305 0.33808919
  0.27973183 0.18476998 0.08152502 0.45340312 0.38000742 0.45042762
  0.67295891 0.44541759 0.57470178 0.58274583 0.33284681 0.48496762
  0.13754567 0.41154333 0.6942787  0.09374229 0.53704266 0.62553639
  0.15944925 0.28424579 0.30338548 0.67059746 0.74472609 0.57825137
  0.52185206 0.52559183 0.34232405 0.43020726 0.38233557 0.4192966
  0.3434875  0.27794518 0.11725914 0.24497161 0.63406339 0.67044743
  0.60199164 0.31920819 0.11690715 0.44946856 0.29

In [253]:

Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32)

print(Z)


[0 1 2 3 4 5 6 7 8 9]


In [254]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [255]:

X, Y = np.meshgrid(np.linspace(-1,1,10),
                   np.linspace(-1,1,10))

D = np.sqrt(X*X + Y*Y)
sigma = 1.0

G = np.exp(-(D**2)/(2*sigma**2))

print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [256]:
n = 10
p = 5

Z = np.zeros((n,n))

indices = np.random.choice(n*n, p, replace=False)
Z.flat[indices] = 1

print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [257]:
Z = np.random.random((5,10))
Z -= Z.mean(axis=1, keepdims=True)

print(Z)

[[-0.12129951  0.33751902 -0.05955406  0.23366441 -0.20715319  0.06426074
  -0.47457444  0.23020938 -0.0918649   0.08879255]
 [-0.04742226 -0.4747951   0.0095551  -0.33641586  0.07986406 -0.11334662
  -0.14626959  0.24679341  0.50265035  0.27938652]
 [-0.22692638  0.16320736 -0.06500551 -0.2976973   0.07117601 -0.066926
   0.52690226  0.33250337 -0.18932469 -0.24790911]
 [-0.25634467  0.09916177 -0.39915692  0.50003703 -0.33883932 -0.2556616
  -0.12152271  0.20267333  0.38219366  0.18745943]
 [-0.29424085  0.08428995 -0.20402335  0.10496656 -0.11007295 -0.26182477
   0.1167991   0.19752648  0.11587302  0.2507068 ]]


In [258]:
Z = np.random.randint(0,20,(5,5))
n = 2

Z = Z[Z[:,n].argsort()]

print(Z)

[[10  0  1  5  8]
 [ 8 14  6  5 14]
 [ 4 15  7  6  9]
 [13 14  8 19  9]
 [11 19 19 12 12]]


In [259]:
Z = np.random.randint(0,2,(5,5))

print((~Z.any(axis=0)).any())

# or, print the column numbers:
null_columns = np.where(~Z.any(axis=0))[0]
print(null_columns)


False
[]


In [260]:
Z = np.random.uniform(0, 100, 10)
value = 25

nearest = Z[np.abs(Z - value).argmin()]

print(Z)
print("Nearest value:", nearest)

[58.10674459 12.18014753  3.2496214   5.58759482 46.3378117  40.4934948
 62.42248239 73.62126743 16.25189138 90.73115471]
Nearest value: 16.251891384843432


In [261]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)

it = np.nditer([A, B, None])

for x, y, z in it:
    z[...] = x + y

print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [262]:
class NamedArray(np.ndarray):

    def __new__(cls, array, name="No Name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', "No Name")


Z = NamedArray(np.arange(10), "My Array")

print(Z.name)
print(Z)

My Array
[0 1 2 3 4 5 6 7 8 9]


In [263]:

Z = np.ones(10)
I = np.array([1,1,3,3,3,5])
np.add.at(Z, I, 1)

print(Z)


[1. 3. 1. 4. 1. 2. 1. 1. 1. 1.]


In [264]:
X = np.array([1,2,3,4,5])
I = np.array([0,1,1,2,2])

F = np.zeros(3)
np.add.at(F, I, X)

print(F)

[1. 5. 9.]


In [265]:
image = np.random.randint(0,256,(100,100,3),dtype=np.uint8)

unique = len(np.unique(image.reshape(-1,3), axis=0))

print(unique)

9997


In [266]:
Z = np.random.randint(0,10,(2,3,4,5))

result = Z.sum(axis=(-2,-1))

print(result)


[[102  77  91]
 [ 78  83  70]]


In [267]:
D = np.array([10,20,30,40,50,60])
S = np.array([0,0,1,1,2,2])

means = np.bincount(S, weights=D) / np.bincount(S)

print(means)

[15. 35. 55.]


In [268]:
A = np.random.random((5,5))
B = np.random.random((5,5))

diag = np.einsum('ij,ji->i', A, B)

print(diag)

# Alternative
diag = np.diag(np.dot(A,B))


[1.1125158  0.57225253 1.29869671 1.51748856 1.39111307]


In [269]:
Z = np.array([1,2,3,4,5])

R = np.zeros(len(Z)*4-3)
R[::4] = Z

print(R)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [270]:

A = np.ones((5,5,3))
B = np.random.random((5,5))

result = A * B[:,:,None]

print(result.shape)

(5, 5, 3)


In [271]:
Z = np.arange(25).reshape(5,5)
Z[[0,4]] = Z[[4,0]]

print(Z)

[[20 21 22 23 24]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [272]:
triangles = np.random.randint(0,20,(10,3))

edges = np.sort(
    np.vstack([
        triangles[:,[0,1]],
        triangles[:,[1,2]],
        triangles[:,[2,0]]
    ]),
    axis=1
)

unique_edges = np.unique(edges, axis=0)

print(unique_edges)


[[ 0  2]
 [ 0 13]
 [ 0 19]
 [ 1  3]
 [ 1  9]
 [ 1 13]
 [ 1 14]
 [ 2  3]
 [ 2 10]
 [ 2 15]
 [ 2 19]
 [ 3  4]
 [ 3  6]
 [ 3  9]
 [ 3 10]
 [ 3 13]
 [ 4 10]
 [ 4 14]
 [ 4 17]
 [ 6 13]
 [10 12]
 [10 14]
 [12 14]
 [13 14]
 [13 19]
 [14 17]
 [15 19]]


In [273]:

C = np.array([2,1,3])

A = np.repeat(np.arange(len(C)), C)

print(A)

[0 0 1 2 2 2]


In [274]:

Z = np.arange(10)
window = 3

result = np.convolve(Z,
                     np.ones(window)/window,
                     mode='valid')

print(result)


[1. 2. 3. 4. 5. 6. 7. 8.]


In [275]:

Z = np.arange(1,15)

R = np.lib.stride_tricks.sliding_window_view(Z,3)

print(R)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]]


In [276]:
Z = np.array([True,False,True])
np.logical_not(Z,out=Z)

print(Z)

# Float case
Z = np.array([1.,2.,3.])
np.negative(Z,out=Z)

[False  True False]


array([-1., -2., -3.])

In [277]:
P0 = np.random.random((5,2))
P1 = np.random.random((5,2))
p = np.random.random(2)

distance = np.abs(
    np.cross(P1-P0,p-P0)
)/np.linalg.norm(P1-P0,axis=1)

print(distance)

[0.02035687 0.1938397  0.42986653 0.81269554 0.18863918]


/tmp/ipykernel_1277/3782910164.py:6: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(P1-P0,p-P0)


In [278]:

P0 = np.random.random((5,2))
P1 = np.random.random((5,2))
P = np.random.random((10,2))

distance = np.abs(
    np.cross(P1-P0,P[:,None]-P0)
)/np.linalg.norm(P1-P0,axis=1)

print(distance)


[[0.06851376 0.33807542 0.07083896 0.45269707 0.45837933]
 [0.50842405 0.17079884 0.04959963 0.09771477 0.08384627]
 [0.56587083 0.45061042 0.51179548 0.02918209 0.30885959]
 [0.23802231 0.22075794 0.30756143 0.07787093 0.28452111]
 [0.77522841 0.2770129  0.14837933 0.42174945 0.23823194]
 [0.81217163 0.35240737 0.05655772 0.4339514  0.30490387]
 [0.65325027 0.2635511  0.01109011 0.2547151  0.19384492]
 [0.35123325 0.08309311 0.11687025 0.07966822 0.02586676]
 [0.81228278 0.27401758 0.21074239 0.47630438 0.246428  ]
 [0.82353899 0.53049928 0.27601981 0.35433295 0.44102507]]


/tmp/ipykernel_1277/3759462266.py:6: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(P1-P0,P[:,None]-P0)


In [279]:
Z = np.arange(1,15)

R = np.lib.stride_tricks.sliding_window_view(Z,4)

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [280]:
Z = np.random.randint(0,10,(5,5))

rank = np.linalg.matrix_rank(Z)

print(rank)


5


In [281]:
Z = np.random.randint(0,10,50)

print(np.bincount(Z).argmax())


3


In [282]:
Z = np.random.randint(0,10,(10,10))

blocks = np.lib.stride_tricks.sliding_window_view(Z,(3,3))

print(blocks.shape)

(8, 8, 3, 3)


In [283]:
class Symmetric(np.ndarray):

    def __setitem__(self,index,value):
        i,j = index
        super().__setitem__((i,j),value)
        super().__setitem__((j,i),value)

Z = np.zeros((5,5)).view(Symmetric)
Z[1,3] = 10

print(Z)


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [284]:

P = 5
n = 3

A = np.random.random((P,n,n))
B = np.random.random((P,n,1))

result = np.einsum('ijk,ikl->jl',A,B)

print(result)

[[2.47049426]
 [2.81912231]
 [4.04877243]]


In [285]:
Z = np.ones((16,16))

result = Z.reshape(4,4,4,4).sum(axis=(1,3))

print(result)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [286]:
def iterate(Z):

    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]               + Z[1:-1,2:] +
         Z[2:,0:-2] + Z[2:,1:-1] + Z[2:,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)

    survive = ((N==2)|(N==3)) & (Z[1:-1,1:-1]==1)

    Z[...] = 0

    Z[1:-1,1:-1][birth|survive] = 1

    return Z

Z = np.random.randint(0,2,(10,10))

print(iterate(Z))

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 1 1 1 1 1 0]
 [0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 1 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [287]:
Z = np.random.randint(0,100,20)
n = 5

print(np.sort(Z)[-n:])

# or
print(Z[np.argpartition(Z,-n)[-n:]])

[80 89 96 97 99]
[80 89 96 97 99]


In [288]:

A = np.array([1,2])
B = np.array([3,4])

result = np.array(np.meshgrid(A,B)).T.reshape(-1,2)

print(result)

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


In [289]:
Z = np.array([[1,2],[3,4]])

R = np.core.records.fromarrays(Z.T,
                               names='a,b')

print(R)

[(1, 2) (3, 4)]


/tmp/ipykernel_1277/1352706967.py:3: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T,


In [290]:
Z = np.arange(10)

print(Z**3)
print(np.power(Z,3))
print(np.einsum('i,i,i->i',Z,Z,Z))


[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]


In [291]:

A = np.random.randint(0,5,(8,3))
B = np.array([[1,2],
              [0,3]])

result = np.array([
    np.isin(A,row).sum(axis=1)==len(row)
    for row in B
])

print(result)

[[False False False False False  True False  True]
 [False  True False False False False  True False]]


In [292]:
Z = np.random.randint(0,5,(10,3))

result = Z[(Z[:,0]!=Z[:,1]) |
           (Z[:,1]!=Z[:,2])]

print(result)


[[1 3 0]
 [4 2 2]
 [3 1 4]
 [0 1 4]
 [4 2 0]
 [4 4 3]
 [0 4 1]
 [1 4 0]
 [1 4 1]
 [2 3 3]]


In [293]:
Z = np.array([0,1,2,3,4,5,6,7])

binary = ((Z[:,None] &    (1<<np.arange(8)))>0).astype(int)

print(binary)

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [0 1 1 0 0 0 0 0]
 [1 1 1 0 0 0 0 0]]


In [294]:
Z = np.random.randint(0,5,(10,3))

unique = np.unique(Z,axis=0)

print(unique)

[[0 0 3]
 [0 1 4]
 [1 0 1]
 [1 0 4]
 [2 2 0]
 [2 4 1]
 [3 1 3]
 [3 2 1]
 [4 1 4]
 [4 4 0]]


In [295]:

A = np.arange(5)
B = np.arange(5)

# Inner product
print(np.einsum('i,i',A,B))

# Outer product
print(np.einsum('i,j->ij',A,B))

# Sum
print(np.einsum('i->',A))

# Element-wise multiplication
print(np.einsum('i,i->i',A,B))


30
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
10
[ 0  1  4  9 16]


In [296]:
X = np.array([0,1,2,3])
Y = np.array([0,2,1,3])

distance = np.sqrt(np.diff(X)**2 +
                   np.diff(Y)**2)

cumdist = np.insert(np.cumsum(distance),0,0)

samples = np.linspace(0,cumdist[-1],10)

newX = np.interp(samples,cumdist,X)
newY = np.interp(samples,cumdist,Y)

print(newX)
print(newY)

[0.         0.29249506 0.58499012 0.87748518 1.26876235 1.73123765
 2.12251482 2.41500988 2.70750494 3.        ]
[0.         0.58499012 1.16998024 1.75497035 1.73123765 1.26876235
 1.24502965 1.83001976 2.41500988 3.        ]


In [297]:
n = 5

X = np.array([[2,2,1],
              [1,1,1],
              [3,1,1]])

result = X[(X.sum(axis=1)==n) &
           (X.astype(int)==X).all(axis=1)]

print(result)

[[2 2 1]
 [3 1 1]]


In [298]:
X = np.random.randn(100)
N = 1000

means = np.empty(N)

for i in range(N):
    sample = np.random.choice(X,
                              size=len(X),
                              replace=True)
    means[i] = sample.mean()

CI = np.percentile(means,[2.5,97.5])

print("95% Confidence Interval:",CI)

95% Confidence Interval: [-0.09567838  0.24513985]
